import React, { lazy } from "react";
import Layout from "@app/layouts";
import Authenticated from "@app/Guard/Authenticated.jsx";
import Guest from "@app/Guard/Guest.jsx";
import { useCryptoLocalStorage } from "../utils/hooks/useCryptoLocalStorage";
// import LLL from  "../modules/login/Login"
function manageRoutePath() {
  const LLL = React.lazy(() => import("../modules/login/Login"));
  const allRoutes = [
    // {
    //   Guard: Authenticated,
    //   layout: Layout,
    //   path: "/DirectPatientReg",
    //   component: lazy(
    //     () => import("@app/pages/frontOffice/PatientRegistration/Index.jsx")
    //   ),
    //   exact: true,
    // },
    {
      Guard: Authenticated,
      layout: Layout,
      path: "/myview",
      component: lazy(() => import("@app/pages/MyView.jsx")),
      exact: true,
    },
    {
      Guard: Authenticated,
      layout: Layout,
      path: "/Circular",
      component: lazy(() => import("@app/pages/Circular.jsx")),
      exact: true,
    },
    {
      Guard: Authenticated,
      layout: Layout,
      path: "/FeedBack",
      component: lazy(() => import("@app/pages/FeedBack.jsx")),
      exact: true,
    },
    {
      Guard: Authenticated,
      layout: Layout,
      path: "/viewissues",
      component: lazy(() => import("@app/pages/ViewIssues.jsx")),
      exact: true,
    },
    {
      Guard: Authenticated,
      layout: Layout,
      path: "/AttendanceReport",
      component: lazy(() => import("@app/pages/AttendanceReport.jsx")),
      exact: true,
    },
    {
      Guard: Authenticated,
      layout: Layout,
      path: "/Summary",
      component: lazy(() => import("@app/pages/Summary.jsx")),
      exact: true,
    },

    {
      Guard: Authenticated,
      layout: Layout,
      path: "/FeedbackList",
      component: lazy(() => import("@app/pages/FeedbackList.jsx")),
      exact: true,
    },
    {
      Guard: Authenticated,
      layout: Layout,
      path: "/EmployeeFeedback",
      component: lazy(() => import("@app/pages/EmployeeFeedback.jsx")),
      exact: true,
    },
    {
      Guard: Authenticated,
      layout: Layout,
      path: "/EmailerView",
      component: lazy(() => import("@app/pages/EmailerView.jsx")),
      exact: true,
    },
    {
      Guard: Authenticated,
      layout: Layout,
      path: "/TechnicalSupportAgreement",
      component: lazy(() => import("@app/pages/TechnicalSupportAgreement.jsx")),
      exact: true,
    },
    {
      Guard: Authenticated,
      layout: Layout,
      path: "/SalesLead",
      component: lazy(() => import("@app/pages/SalesLead.jsx")),
      exact: true,
    },
    {
      Guard: Authenticated,
      layout: Layout,
      path: "/SalesLeadCreate",
      component: lazy(() => import("@app/pages/SalesLeadCreate.jsx")),
      exact: true,
    },
    {
      Guard: Authenticated,
      layout: Layout,
      path: "/BulkNewTicketNotes",
      component: lazy(() => import("@app/pages/BulkNewTicketNotes.jsx")),
      exact: true,
    },
    {
      Guard: Authenticated,
      layout: Layout,
      path: "/AMCSalesBooking",
      component: lazy(() => import("@app/pages/AMCSalesBooking.jsx")),
      exact: true,
    },
    {
      Guard: Authenticated,
      layout: Layout,
      path: "/NewTicketClient",
      component: lazy(() => import("@app/pages/NewTicketClient.jsx")),
      exact: true,
    },
    {
      Guard: Authenticated,
      layout: Layout,
      path: "/ViewTicketClient",
      component: lazy(() => import("@app/pages/ViewTicketClient.jsx")),
      exact: true,
    },
    {
      Guard: Authenticated,
      layout: Layout,
      path: "/ClientFeedbackFlow",
      component: lazy(() => import("@app/pages/ClientFeedbackFlow.jsx")),
      exact: true,
    },
    {
      Guard: Authenticated,
      layout: Layout,
      path: "/EmployeeFeedbackDashboard",
      component: lazy(() => import("@app/pages/EmployeeFeedbackDashboard.jsx")),
      exact: true,
    },
    {
      Guard: Authenticated,
      layout: Layout,
      path: "/DeveloperCalendar",
      component: lazy(() => import("@app/pages/CRM/DeveloperCalendar.jsx")),
      exact: true,
    },
    {
      Guard: Authenticated,
      layout: Layout,
      path: "/TicketView",
      component: lazy(() => import("@app/pages/TicketView.jsx")),
      exact: true,
    },
    {
      Guard: Authenticated,
      layout: Layout,
      path: "/newdeveloperCalendar",
      component: lazy(
        () => import("@app/pages/DeveloperCalendar/DeveloperCalender.jsx")
      ),
      exact: true,
    },
    {
      Guard: Authenticated,
      layout: Layout,
      path: "/EmployeeMaster",
      component: lazy(() => import("@app/pages/EmployeeMaster.jsx")),
      exact: true,
    },
    {
      Guard: Authenticated,
      layout: Layout,
      path: "/SearchEmployeeMaster",
      component: lazy(() => import("@app/pages/SearchEmployeeMaster.jsx")),
      exact: true,
    },
    {
      Guard: Authenticated,
      layout: Layout,
      path: "/SearchProjectMaster",
      component: lazy(() => import("@app/pages/SearchProjectMaster.jsx")),
      exact: true,
    },

    {
      Guard: Authenticated,
      layout: Layout,
      path: "/ImplementationPlan",
      component: lazy(() => import("@app/pages/ImplementationPlan.jsx")),
      exact: true,
    },
    {
      Guard: Authenticated,
      layout: Layout,
      path: "/ManageOrdering",
      component: lazy(() => import("@app/pages/ManageOrdering.jsx")),
      exact: true,
    },
    {
      Guard: Authenticated,
      layout: Layout,
      path: "/SearchAmountSubmission",
      component: lazy(() => import("@app/pages/SearchAmountSubmission.jsx")),
      exact: true,
    },
    {
      Guard: Authenticated,
      layout: Layout,
      path: "/CircularSearch",
      component: lazy(() => import("@app/pages/CircularSearch.jsx")),
      exact: true,
    },
    {
      Guard: Authenticated,
      layout: Layout,
      path: "/SearchConnectorRequest",
      component: lazy(() => import("@app/pages/SearchConnectorRequest.jsx")),
      exact: true,
    },
    {
      Guard: Authenticated,
      layout: Layout,
      path: "/SalesBooking",
      component: lazy(() => import("@app/pages/SalesBooking.jsx")),
      exact: true,
    },
    {
      Guard: Authenticated,
      layout: Layout,
      path: "/TaxInvoiceView",
      component: lazy(() => import("@app/pages/TaxInvoiceView.jsx")),
      exact: true,
    },
    {
      Guard: Authenticated,
      layout: Layout,
      path: "/QuotationBooking",
      component: lazy(() => import("@app/pages/QuotationBooking.jsx")),
      exact: true,
    },
    {
      Guard: Authenticated,
      layout: Layout,
      path: "/Attendance",
      component: lazy(() => import("@app/pages/CRM/Attendance.jsx")),
      exact: true,
    },
    {
      Guard: Authenticated,
      layout: Layout,
      path: "/CrmDashboard",
      component: lazy(() => import("@app/pages/CRM/CrmDashboard.jsx")),
      exact: true,
    },

    {
      Guard: Authenticated,
      layout: Layout,
      path: "/LeaveRequest",
      component: lazy(() => import("@app/pages/LeaveRequest.jsx")),
      exact: true,
    },
    {
      Guard: Authenticated,
      layout: Layout,
      path: "/LeaveViewApproval",
      component: lazy(() => import("@app/pages/LeaveViewApproval.jsx")),
      exact: true,
    },
    {
      Guard: Authenticated,
      layout: Layout,
      path: "/ShowEmployee",
      component: lazy(() => import("@app/pages/CRM/ShowEmployee.jsx")),
      exact: true,
    },
    {
      Guard: Authenticated,
      layout: Layout,
      path: "/ShowWorkingDays",
      component: lazy(() => import("@app/pages/CRM/ShowWorkingDays.jsx")),
      exact: true,
    },
    {
      Guard: Authenticated,
      layout: Layout,
      path: "/AdvanceRequest",
      component: lazy(() => import("@app/pages/CRM/AdvanceRequest.jsx")),
      exact: true,
    },
    {
      Guard: Authenticated,
      layout: Layout,
      path: "/SupplierMaster",
      component: lazy(() => import("@app/pages/Inventory/SupplierMaster.jsx")),
      exact: true,
    },
    {
      Guard: Authenticated,
      layout: Layout,
      path: "/ItemMaster",
      component: lazy(() => import("@app/pages/Inventory/ItemMaster.jsx")),
      exact: true,
    },
    {
      Guard: Authenticated,
      layout: Layout,
      path: "/GRN",
      component: lazy(() => import("@app/pages/Inventory/GRN.jsx")),
      exact: true,
    },
    {
      Guard: Authenticated,
      layout: Layout,
      path: "/SmartReport",
      component: lazy(() => import("@app/pages/SmartReport/SmartReport.jsx")),
      exact: true,
    },
    {
      Guard: Authenticated,
      layout: Layout,
      path: "/AdvanceRequestView",
      component: lazy(() => import("@app/pages/CRM/AdvanceRequestView.jsx")),
      exact: true,
    },
    {
      Guard: Authenticated,
      layout: Layout,
      path: "/ViewEmployeeExpense",
      component: lazy(() => import("@app/pages/CRM/ViewEmployeeExpense.jsx")),
      exact: true,
    },
    {
      Guard: Authenticated,
      layout: Layout,
      path: "/EmployeeChangePassword",
      component: lazy(() => import("@app/pages/EmployeeChangePassword.jsx")),
      exact: true,
    },
    {
      Guard: Authenticated,
      layout: Layout,
      path: "/ProjectMaster",
      component: lazy(() => import("@app/pages/ProjectMaster.jsx")),
      exact: true,
    },
    {
      Guard: Authenticated,
      layout: Layout,
      path: "/ImplementationStepMaster",
      component: lazy(() => import("@app/pages/ImplementationStepMaster.jsx")),
      exact: true,
    },
    {
      Guard: Authenticated,
      layout: Layout,
      path: "/VideoPlayerMaster",
      component: lazy(() => import("@app/pages/VideoPlayerMaster.jsx")),
      exact: true,
    },
    {
      Guard: Authenticated,
      layout: Layout,
      path: "/DashboardConfiguration",
      component: lazy(() => import("@app/pages/DashboardConfiguration.jsx")),
      exact: true,
    },
    {
      Guard: Authenticated,
      layout: Layout,
      path: "/Master",
      component: lazy(() => import("@app/pages/Master.jsx")),
      exact: true,
    },
    {
      Guard: Authenticated,
      layout: Layout,
      path: "/MasterType",
      component: lazy(() => import("@app/pages/MasterType.jsx")),
      exact: true,
    },
    {
      Guard: Authenticated,
      layout: Layout,
      path: "/GlobalMaster",
      component: lazy(() => import("@app/pages/GlobalMaster.jsx")),
      exact: true,
    },
    {
      Guard: Authenticated,
      layout: Layout,
      path: "/UserVSProjectMapping",
      component: lazy(() => import("@app/pages/UserVSProjectMapping.jsx")),
      exact: true,
    },
    {
      Guard: Authenticated,
      layout: Layout,
      path: "/UserVsModuleMapping",
      component: lazy(() => import("@app/pages/UserVsModuleMapping.jsx")),
      exact: true,
    },
    {
      Guard: Authenticated,
      layout: Layout,
      path: "/ChangeSubmitDateofTicket",
      component: lazy(() => import("@app/pages/ChangeSubmitDateofTicket.jsx")),
      exact: true,
    },
    {
      Guard: Authenticated,
      layout: Layout,
      path: "/QueryVsResultMaster",
      component: lazy(() => import("@app/pages/QueryVsResultMaster.jsx")),
      exact: true,
    },
    {
      Guard: Authenticated,
      layout: Layout,
      path: "/AccessRight",
      component: lazy(() => import("@app/pages/AccessRight.jsx")),
      exact: true,
    },
    {
      Guard: Authenticated,
      layout: Layout,
      path: "/MorningWish",
      component: lazy(() => import("@app/pages/MorningWish.jsx")),
      exact: true,
    },
    {
      Guard: Authenticated,
      layout: Layout,
      path: "/BirthdayWish",
      component: lazy(() => import("@app/pages/BirthdayWish.jsx")),
      exact: true,
    },
    {
      Guard: Authenticated,
      layout: Layout,
      path: "/ConnectorRequest",
      component: lazy(() => import("@app/pages/ConnectorRequest.jsx")),
      exact: true,
    },
    {
      Guard: Authenticated,
      layout: Layout,
      path: "/AmountSubmission",
      component: lazy(() => import("@app/pages/AmountSubmission.jsx")),
      exact: true,
    },
    {
      Guard: Authenticated,
      layout: Layout,
      path: "/LedgerStatus",
      component: lazy(() => import("@app/pages/LedgerStatus.jsx")),
      exact: true,
    },
    {
      Guard: Authenticated,
      layout: Layout,
      path: "/Ledger",
      component: lazy(() => import("@app/pages/Ledger.jsx")),
      exact: true,
    },
    {
      Guard: Authenticated,
      layout: Layout,
      path: "/LedgerTransaction",
      component: lazy(() => import("@app/pages/LedgerTransaction.jsx")),
      exact: true,
    },
    {
      Guard: Authenticated,
      layout: Layout,
      path: "/UploadDocument",
      component: lazy(() => import("@app/pages/UploadDocument.jsx")),
      exact: true,
    },
    {
      Guard: Authenticated,
      layout: Layout,
      path: "/PatientBlackList",
      component: lazy(
        () =>
          import(
            "@app/pages/frontOffice/PatientRegistration/PatientBlackList.jsx"
          )
      ),
      exact: true,
    },
    {
      Guard: Authenticated,
      layout: Layout,
      path: "/dashboard",
      component: lazy(() => import("@app/pages/Dashboard.jsx")),
      exact: true,
    },
    {
      Guard: Authenticated,
      layout: Layout,
      path: "/CoordinatorDashboard",
      component: lazy(() => import("@app/pages/CoordinatorDashboard.jsx")),
      exact: true,
    },
    {
      Guard: Authenticated,
      layout: Layout,
      path: "/ManagerDashboard",
      component: lazy(() => import("@app/pages/ManagerDashboard.jsx")),
      exact: true,
    },
    {
      Guard: Authenticated,
      layout: Layout,
      path: "/HrDashboard",
      component: lazy(() => import("@app/pages/HrDashboard.jsx")),
      exact: true,
    },

    {
      Guard: Guest,
      path: "/login",
      component: LLL,
      exact: true,
    },
    {
      path: "/ForgetPassword",
      component: lazy(() => import("@app/modules/login/ForgetPassword.jsx")),
      exact: true,
    },

    {
      Guard: Authenticated,
      layout: Layout,
      path: "/myview",
      component: lazy(() => import("@app/pages/MyView.jsx")),
      exact: true,
    },
    {
      Guard: Authenticated,
      layout: Layout,
      path: "/viewissues",
      component: lazy(() => import("@app/pages/ViewIssues.jsx")),
      exact: true,
    },
    {
      Guard: Authenticated,
      layout: Layout,
      path: "/Summary",
      component: lazy(() => import("@app/pages/Summary.jsx")),
      exact: true,
    },
    {
      Guard: Authenticated,
      layout: Layout,
      path: "/reportissue",
      component: lazy(() => import("@app/pages/ReportIssue.jsx")),
      exact: true,
    },
    {
      Guard: Authenticated,
      layout: Layout,
      path: "/AutoBackupStatusSheet",
      component: lazy(() => import("@app/pages/AutoBackupStatusSheet.jsx")),
      exact: true,
    },
    {
      Guard: Authenticated,
      layout: Layout,
      path: "/CollectionSheet",
      component: lazy(() => import("@app/pages/CollectionSheet.jsx")),
      exact: true,
    },
    {
      Guard: Authenticated,
      layout: Layout,
      path: "/AgeingSheet",
      component: lazy(() => import("@app/pages/AgeingSheet.jsx")),
      exact: true,
    },
    {
      Guard: Authenticated,
      layout: Layout,
      path: "/QuotationMaster",
      component: lazy(() => import("@app/pages/QuotationMaster.jsx")),
      exact: true,
    },
  ];
  return allRoutes;
}

export default manageRoutePath;
